### ISSUE TITLE
alloyeditor-ocean.svg doesn't exist

### ISSUE THREAD

**Issue by Dattaya** [ipeychev/alloyeditor-react-component#1]
Hi!
https://github.com/ipeychev/alloyeditor-react-component/blob/master/dist/alloyeditor/assets/alloy-editor-ocean.css#L7 :

``` css
@font-face {
  ...
  url('fonts/alloyeditor-ocean.svg#alloyeditor-ocean') format('svg');
}
```

Could you please either provide this file or remove that line, otherwise `webpack-isomorphic-tools` complains that the file doesn't exists, and indeed, I don't see it in the fonts folder https://github.com/ipeychev/alloyeditor-react-component/tree/master/dist/alloyeditor/assets/fonts.

**Comment by ipeychev** [comment]
Okay, makes sense. This is an issue in the editor itself, I just created an issue [there](https://github.com/liferay/alloy-editor/issues/428).

**Comment by Dattaya** [comment]
Thank you @ipeychev ! I guess this one can be closed as it's an upstream issue.

**Comment by ipeychev** [comment]
Fixed [here](https://github.com/liferay/alloy-editor/issues/428)
