### ISSUE TITLE
Add example of how to listen to events and read state in React-y way

### ISSUE THREAD

**Issue by timraasveld** [ipeychev/alloyeditor-react-component#3]
I'm trying to figure out how to listen to events in a React way. Right now I'm adding an event listener in the CKEditor way.

``` javascript
var AlloyEditorView = React.createClass({
  componentDidMount: function() {
    this._editor = AlloyEditor.editable(this.props.id, this.props.alloyEditorConfig);
    CKEDITOR.instances[this.props.id].on('blur', this.props.onBlur)
  }
)};
```

And then in my event handler to read the data:

``` javascript
CKEDITOR.instances[this.props.id].getData();
```

However, this obviously isn't very React-y since this way it's impossible to treat the editable text as component state. I would rather do something like `this.props.text` and have AlloyEditor return the text.

Would you please be so kind to add an example of how to listen to events and access text state in a React way?

If this is not possible in the current version, I might have a shot add creating a reusable AlloyEditor mixin that glues CKEditor and React together even more :)

**Comment by ipeychev** [comment]
Hello,

Yeah, this is the way to do it - you listen to CKEditor's events and update the component's state accordingly. As you said, it could be done even with a mixin. Looking on the code above, you may simplify it in this way:

``` javascript
// the code comes on top of my head, but it should work
var AlloyEditorView = React.createClass({
  componentDidMount: function() {
    this._alloyEditor = AlloyEditor.editable(this.props.id, this.props.alloyEditorConfig);
    // `nativeEditor` attribute returns the created CKEditor instance, so
    // there is no need to look for it in CKEditor's instances
    this._nativeEditor = this._alloyEditor.get('nativeEditor'); 

   // here you can subscribe to whatever event you want
    this._nativeEditor.on('blur', this.props.onBlur);

    // get the data
    var currentData = this._nativeEditor.getData();
  }
)};
```

In the current version we don't provide an example or mixin, and this is not for any other reason, but because no one required any :) Feel free to contribute one and we will publish it on the site!

Thanks,

**Comment by timraasveld** [comment]
Great - thanks for the explanation. Calling `this._alloyeditor.get('nativeEditor');` seems like a much cleaner way to get the CKEditor instance.

I'll get started making a React mixin soon and create a PR when it's done!

**Comment by ipeychev** [comment]
Great!

**Comment by ipeychev** [comment]
:+1:
