### ISSUE TITLE
Add example for using Webpack

### ISSUE THREAD

**Issue by harel** [ipeychev/alloyeditor-react-component#5]
I'm trying to incorporate Alloy into a React app using webpack / npm. 
All is fine though I can't make it 'find' the CK editor using the paths you set up as global variables. 
The alloyeditor directory is in node_modules and I rather not include a whole alloy dir inside my project in the same way the example is showing. 
Any ideas on how this can work?

**Comment by ipeychev** [comment]
Hello,

There shouldn't be any difference - the directory is the same as those in node_modules. I just tried and it works fine:
1. I opened the `index.html` and changed the code there like this:

```
   <script>
      window.ALLOYEDITOR_BASEPATH = '../node_modules/alloyeditor/dist/alloy-editor/';
      window.CKEDITOR_BASEPATH = '../node_modules/alloyeditor/dist/alloy-editor/';
    </script>
```

Then I compiled and opened `index.html` again. It worked fine.

Hope that helps, please feel free to reopen this issue if it doesn't.

Thanks,

**Comment by harel** [comment]
I've tried this already, and the problem is that my app is not exposing node_modules like that.

`GET http://localhost:8000/node_modules/alloyeditor/dist/alloy-editor/lang/alloy-editor/en-gb.js?t=FB9E` doesn't resolve, and its also trying to load resource like `GET http://localhost:8000/email/config.js?t=FB9E` which simply do not exist. Note that react-router doesn't have routes for those urls. 

As well, CKEditor complains its incorrectly destroyed when I have the destroy call on unmount: 

`[CKEDITOR] Error code: editor-incorrect-destroy.`

This is my component below: 

```
'use strict';

import React from 'react';
import ReactDOM from 'react-dom';
import AlloyEditor from 'alloyeditor';

window.ALLOYEDITOR_BASEPATH = '../node_modules/alloyeditor/dist/alloy-editor/';
window.CKEDITOR_BASEPATH = '../node_modules/alloyeditor/dist/alloy-editor/';

const Composer = React.createClass({ 
    getInitialState: function() {
        return {
            value: 'This is <h1>initial</h1>value \n<P> so lets <b>go</b>'
        }
    },

    componentDidMount: function() {
        this._editor = AlloyEditor.editable(this.props.container, this.props.alloyEditorConfig);
    },

    componentWillUnmount: function() {
        this._editor.destroy();
    },

    render: function() {
        return (
            <div id={this.props.container}> 
                            {this.state.value}
            </div>
        );
    }
});

export default Composer;

```

and its called via `<Composer container="composer"/>`

**Comment by ipeychev** [comment]
Hello,

Well, AlloyEditor should be visible from somewhere - either from node_modules, or from the dist folder - otherwise there is no way for it to pick the correct language, etc.
React router I don't believe it has something to do here, does it?

The request for email I don't know from where it is, maybe there is additional plugin installed?

About destroying, on top of my head I think this is caused because mount is called and then immediately unmount. Since CKEditor didn't have time to pick resources and to initialize properly, it screams that someone killed it before to be ready to live or die. This also could be caused by the fact, that resources were not fetched properly. In any case, it will disappear once it has access to them and if you are not destroying it immediately for some reason, or course.

Hour that helps!

**Comment by harel** [comment]
The current browser path when the control is created is /email. Its trying to load config.js for some reason, hence the /email path. 
I wonder if If I import CKEditor myself beforehand , if that would make a difference...

**Comment by harel** [comment]
The reason I mentioned react-router is because all the app's urls are going through it.

**Comment by harel** [comment]
Would it be possible to instantiate CKEditor in the component and avoid the globals and having to provide it with file access etc?

**Comment by harel** [comment]
In any case, even when I synmlink the node_modules dir and it is accessible, i'm getting those errors coming out of alloy: 

```
GET http://localhost:8000/email/config.js?t=FB9E                             alloy-editor-no-react.js:95 
CKEDITOR.tools.extend.append @ alloy-editor-no-react.js:95CKEDITOR.tools.extend.appendTo @ alloy-editor-no-react.js:71u @ alloy-editor-no-react.js:241CKEDITOR.scriptLoader.load @ alloy-editor-no-react.js:241a @ alloy-editor-no-react.js:242CKEDITOR.scriptLoader.queue @ alloy-editor-no-react.js:242h @ alloy-editor-no-react.js:254l @ alloy-editor-no-react.js:256(anonymous function) @ alloy-editor-no-react.js:252(anonymous function) @ alloy-editor-no-react.js:40
alloy-editor-no-react.js:95 GET http://localhost:8000/email/skins/moono/editor.css?t=FB9E CKEDITOR.tools.extend.append @ alloy-editor-no-react.js:95CKEDITOR.tools.extend.appendStyleSheet @ alloy-editor-no-react.js:85b @ alloy-editor-no-react.js:494CKEDITOR.skin.loadPart @ alloy-editor-no-react.js:496q @ alloy-editor-no-react.js:256(anonymous function) @ alloy-editor-no-react.js:256q @ alloy-editor-no-react.js:22CKEDITOR.event.CKEDITOR.event.fire @ alloy-editor-no-react.js:24CKEDITOR.editor.CKEDITOR.editor.fire @ alloy-editor-no-react.js:25CKEDITOR.event.CKEDITOR.event.fireOnce @ alloy-editor-no-react.js:24CKEDITOR.editor.CKEDITOR.editor.fireOnce @ alloy-editor-no-react.js:25h @ alloy-editor-no-react.js:254(anonymous function) @ alloy-editor-no-react.js:254c.push.callback @ alloy-editor-no-react.js:242f @ alloy-editor-no-react.js:240z @ alloy-editor-no-react.js:240A @ alloy-editor-no-react.js:240CKEDITOR.env.ie.CKEDITOR.env.version.f.$.onerror @ alloy-editor-no-react.js:241
```

**Comment by ipeychev** [comment]
In this case, are you sure that those variables are exposed _before_ you load AlloyEditor?

See [here](http://docs.cksource.com/CKEditor_3.x/Developers_Guide/Specifying_the_Editor_Path).

Here are some more details:
AlloyEditor actually had nothing to do with these variables. CKEditor needs them. That's why even if you load CKEditor by yourself and then AlloyEditor, it will not make any difference.

Thanks,

**Comment by ipeychev** [comment]
My approach to resolve this would be:
1. I get sure the two needed variables are exposed before alloy AlloyEditor is loaded on the page. Please note if you load AlloyEditor by including the script directly into the page, as shown in "Getting Started" guides, there is no need to expose anything.
2. I get the URL to one of the resources and copy it into browser's address bar, to see if I actually have access to it. This will save you time.
3. I copy AlloyEditor to the place where /email is being served. Once I'm sure the resources are found, I create a symlink, or something like this.

Hope that helps!

**Comment by harel** [comment]
I understand what you're saying but still struggling to get it working. I do appreciate the help very much. The `/email` resource is not a real 'path' in my codebase - its a path handled by react-router. 

I've exposed the variables, and I can get to the alloy files if I put the path in the browser (`/node_modules/alloyeditor/dist/alloy-editor/config.js` for example). All seems ok, but alloy or ckeditor are still trying to load resource from the `/email` base path even though the ALLOYEDITOR_BASEPATH and CKEDITOR_BASEPATH are both exposed and set.

**Comment by harel** [comment]
I got it! I was mistaken to assume that just putting the vars before using alloy would be enough. Turns out putting the CK paths at the top level file solved the problem. 
I'll try to refine this a bit but all is well, thanks for the help!

**Comment by ipeychev** [comment]
You are welcome. Happy it worked for you!

**Comment by harel** [comment]
@ipeychev , is there a chat channel for alloy? or a place to ask more questions relating to alloy itself?

**Comment by ipeychev** [comment]
Hey @harel,

There is currently no chat channel and people usually open issues, which we tag as "help wanted" and "question" or ask by posting comments on the site (these are 1%, the others are 99%).
We were thinking to move these on StackOverflow but they are currently not that much and at least we have a central place for tracking them. If StackOverflow makes more sense, we may redirect the questions there.

Hope that helps,

**Comment by khurrumqureshi** [comment]
@harel can you kindly explain how you resolve this issue as I am facing the same issue. thanks

**Comment by Goodguy0721** [comment]
@harel Hey Could you let me know how to fix CKEDITOR_BASEPATH issues?

**Comment by harel** [comment]
Sorry @Goodguy0721  and @khurrumqureshi  - I missed those "calls" to me to provide more info.

What I did was add this block at my 'index.html' file which is the base of my application. Its "outside" of webpack in a sense but it makes it all work by adding those 'globals':

```
<script type="text/javascript">
	var CKEDITOR_BASEPATH = '/node_modules/alloyeditor/dist/alloy-editor/';
	var ALLOYEDITOR_BASEPATH = '/node_modules/alloyeditor/dist/alloy-editor/';
</script>
```
